language: node_js
node_js:
	- "0.12.9"
	- "4.2.5"
	- "5.5.0"
env:
	- EXPORT_COVERAGE=1 CXX=g++-4.8
addons:
	apt:
		sources:
		- ubuntu-toolchain-r-test
		packages:
		- g++-4.8
branches:
	only:
		- master
